-- Migration: notifications
-- One row per notification delivered to a recipient (user_id). Generated by two
-- events that have a natural recipient in this data model:
--   'follow'  — someone followed you            (actor_id = the follower)
--   'comment' — a new comment landed on a meme   (actor_id = the commenter)
--               you had also commented on        (meme_id = the meme)
--
-- actor_name is denormalised (the actor's display name at emit time) so the feed
-- renders without a join. Like the other tables, ids are plain uuids with no FK.
--
-- Idempotent: `if not exists` makes re-running a no-op.

create table if not exists public.notifications (
  id bigint generated always as identity primary key,
  user_id uuid not null,          -- recipient
  type text not null,             -- 'follow' | 'comment'
  actor_id uuid,                  -- who caused it
  actor_name text,                -- denormalised display name
  meme_id text,                   -- set for 'comment' notifications
  read boolean not null default false,
  created_at timestamptz not null default now()
);

-- Feed query: a user's notifications, newest first.
create index if not exists idx_notifications_user_created
  on public.notifications (user_id, created_at desc);
-- Fast unread badge count.
create index if not exists idx_notifications_unread
  on public.notifications (user_id) where not read;

-- Backend uses the service_role key (bypasses RLS). RLS stays enabled so any
-- direct anon/Google client access is governed by its own policies.
alter table public.notifications enable row level security;
